"""Domain-independent trajectory-informed operator-evolution core."""

from .contracts import (
    DatasetSplit,
    DomainAdapter,
    Evaluator,
    FeatureExtractor,
    Initializer,
    InstanceRef,
    ObjectiveEvaluation,
    SearchContextView,
    SolutionCodec,
    SolutionGuard,
    TraceEncoder,
)
from .search import (
    AcceptancePolicy,
    BlockRandomRoundRobinScheduler,
    GenericSearchKernel,
    OperatorOutcome,
    OperatorScheduler,
    SearchBudget,
    SearchContext,
    SearchOperator,
    SearchResult,
    SearchStep,
    SimulatedAnnealingAcceptance,
)
from .trajectory import OperatorTrace, TrajectoryRecorder, compute_delayed_rewards
from .diagnosis import (
    Diagnoser,
    FeatureCatalog,
    OperatorDiagnoser,
    OperatorProfile,
    SequentialSynergy,
    compute_sequential_synergies,
)
from .validation import (
    ArmMeasurement,
    FitnessPolicy,
    GenericPairedCandidateValidator,
    PairedOutcome,
    ValidationReport,
    abba_timing_order,
    build_crn_seed_schedule,
    compute_fitness,
    decide_retention,
    paired_bootstrap_ci,
    replace_population_slot,
)
from .proposal import (
    CandidateProposalEnvelope,
    DomainCompatibilityError,
    DomainKit,
    DomainSmokeReport,
    ProposalBudgetDeclaration,
    ensure_domain_compatibility,
)
from .evolution import (
    EvolutionArtifactSink,
    EvolutionManagerDependencies,
    EvolutionSplitCapabilities,
    NullEvolutionArtifactSink,
    PopulationFreezeReceipt,
    PopulationSeed,
    population_fingerprint,
)
from .memory import MechanismMemory, MechanismRecord

__all__ = [
    "DatasetSplit",
    "DomainAdapter",
    "Evaluator",
    "FeatureExtractor",
    "Initializer",
    "InstanceRef",
    "ObjectiveEvaluation",
    "SearchContextView",
    "SolutionCodec",
    "SolutionGuard",
    "TraceEncoder",
    "AcceptancePolicy",
    "BlockRandomRoundRobinScheduler",
    "GenericSearchKernel",
    "OperatorOutcome",
    "OperatorScheduler",
    "SearchBudget",
    "SearchContext",
    "SearchOperator",
    "SearchResult",
    "SearchStep",
    "SimulatedAnnealingAcceptance",
    "Diagnoser",
    "FeatureCatalog",
    "OperatorDiagnoser",
    "OperatorProfile",
    "OperatorTrace",
    "SequentialSynergy",
    "TrajectoryRecorder",
    "compute_delayed_rewards",
    "compute_sequential_synergies",
    "ArmMeasurement",
    "FitnessPolicy",
    "GenericPairedCandidateValidator",
    "PairedOutcome",
    "ValidationReport",
    "abba_timing_order",
    "build_crn_seed_schedule",
    "compute_fitness",
    "decide_retention",
    "paired_bootstrap_ci",
    "replace_population_slot",
    "CandidateProposalEnvelope",
    "DomainCompatibilityError",
    "DomainKit",
    "DomainSmokeReport",
    "ProposalBudgetDeclaration",
    "ensure_domain_compatibility",
    "EvolutionArtifactSink",
    "EvolutionManagerDependencies",
    "EvolutionSplitCapabilities",
    "NullEvolutionArtifactSink",
    "PopulationFreezeReceipt",
    "PopulationSeed",
    "population_fingerprint",
    "MechanismMemory",
    "MechanismRecord",
]
