"""Offline JSSP candidate lifecycle used for cross-domain qualification."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass

import numpy as np
from pydantic import BaseModel, ConfigDict

from operator_evolution_core.evolution import (
    PopulationFreezeReceipt,
    population_fingerprint,
)
from operator_evolution_core.proposal import (
    CandidateProposalEnvelope,
    ProposalBudgetDeclaration,
)
from operator_evolution_core.trajectory import TrajectoryRecorder

from .adapter import create_jssp_domain_adapter
from .data import JSSPDatasetSplits
from .operators import (
    CompiledJSSPOperator,
    JSSPDomainKit,
    JSSPOperatorSpec,
    JSSPSmokeFixture,
    initial_operator_population,
    initial_operator_specs,
)
from .validation import JSSPCandidateValidator


class _ReportModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)


class CandidateLifecycleRecord(_ReportModel):
    generation: int
    candidate_index: int
    candidate_id: str
    parent_id: str
    envelope_hash: str
    smoke_passed: bool
    validation_outcomes: int
    parent_mean_best_makespan: float
    candidate_mean_best_makespan: float
    mean_gain: float
    parent_feasibility_rate: float
    candidate_feasibility_rate: float
    median_parent_runtime_ms: float
    median_candidate_runtime_ms: float
    candidate_effective_call_rate: float
    candidate_acceptance_rate: float
    retained: bool
    retention_reasons: list[str]


class JSSPEvolutionSmokeReport(_ReportModel):
    schema_version: str = "jssp-evolution-smoke-v1"
    master_seed: int
    search_calls: int
    generations: int
    candidates_per_generation: int
    validation_instances: int
    runtime_repetitions: int
    initial_population_ids: list[str]
    final_population_ids: list[str]
    candidate_records: list[CandidateLifecycleRecord]
    trace_count: int
    freeze_receipt_id: str
    final_population_fingerprint: str


@dataclass(frozen=True, slots=True)
class JSSPEvolutionSmokeConfig:
    master_seed: int = 20260823
    search_calls: int = 64
    generations: int = 2
    candidates_per_generation: int = 2
    validation_instances: int = 2
    runtime_repetitions: int = 2

    def __post_init__(self) -> None:
        for name in (
            "search_calls",
            "generations",
            "candidates_per_generation",
            "validation_instances",
            "runtime_repetitions",
        ):
            if getattr(self, name) <= 0:
                raise ValueError(f"{name} must be positive")


@dataclass(frozen=True, slots=True)
class JSSPEvolutionSmokeOutcome:
    report: JSSPEvolutionSmokeReport
    freeze_receipt: PopulationFreezeReceipt
    final_population: tuple[CompiledJSSPOperator, ...]
    final_ir_by_id: dict[str, JSSPOperatorSpec]


def _candidate_ir(
    parent: JSSPOperatorSpec,
    generation: int,
    candidate_index: int,
) -> JSSPOperatorSpec:
    payload = parent.model_dump(mode="json")
    candidate_id = f"jssp-g{generation:02d}-c{candidate_index:02d}"
    selector = dict(payload["selector"])
    selector["max_attempts"] = min(
        32,
        int(selector["max_attempts"]) + generation + candidate_index + 1,
    )
    selector["max_distance"] = min(
        128,
        int(selector["max_distance"]) + (generation + 1) * (candidate_index + 1),
    )
    payload.update(
        {
            "operator_id": candidate_id,
            "name": f"JSSP offline candidate g{generation} c{candidate_index}",
            "description": (
                "Deterministic bounded parameter mutation generated by the "
                "offline jssp-v1 designer."
            ),
            "parent_ids": [parent.operator_id],
            "selector": selector,
        }
    )
    return JSSPOperatorSpec.model_validate(payload)


def run_offline_evolution_smoke(
    splits: JSSPDatasetSplits,
    *,
    recorder: TrajectoryRecorder | None = None,
    config: JSSPEvolutionSmokeConfig | None = None,
    parent_slot_order: Sequence[int] | None = None,
    evidence_refs_by_parent: Mapping[str, Sequence[str]] | None = None,
    persist_validation_evidence: bool | None = None,
) -> JSSPEvolutionSmokeOutcome:
    active = config or JSSPEvolutionSmokeConfig()
    kit = JSSPDomainKit()
    adapter = create_jssp_domain_adapter()
    population = list(initial_operator_population())
    specs = {spec.operator_id: spec for spec in initial_operator_specs()}
    initial_ids = [operator.operator_id for operator in population]
    validation = splits.open_validation()[: active.validation_instances]
    fixture_instance = splits.open_train()[0]
    fixture_solution = adapter.initializer.initialize(
        fixture_instance,
        np.random.default_rng(active.master_seed),
    )
    validator = JSSPCandidateValidator(
        search_calls=active.search_calls,
        master_seed=active.master_seed,
        runtime_repetitions=active.runtime_repetitions,
        recorder=recorder,
    )
    records: list[CandidateLifecycleRecord] = []
    slot_order = tuple(parent_slot_order or range(len(population)))
    if not slot_order or any(index < 0 or index >= len(population) for index in slot_order):
        raise ValueError("parent_slot_order must contain valid population indices")
    persist_evidence = (
        recorder is not None
        if persist_validation_evidence is None
        else bool(persist_validation_evidence)
    )
    if persist_evidence and recorder is None:
        raise ValueError("validation evidence persistence requires a recorder")
    for generation in range(active.generations):
        for candidate_index in range(active.candidates_per_generation):
            order_index = (
                generation * active.candidates_per_generation + candidate_index
            ) % len(slot_order)
            slot = slot_order[order_index]
            parent_operator = population[slot]
            parent_ir = specs[parent_operator.operator_id]
            candidate_ir = _candidate_ir(parent_ir, generation, candidate_index)
            envelope = CandidateProposalEnvelope[JSSPOperatorSpec](
                candidate_id=candidate_ir.operator_id,
                domain_id=kit.domain_id,
                ir_version=kit.ir_version,
                parent_ids=[parent_ir.operator_id],
                evidence_refs=list(
                    (evidence_refs_by_parent or {}).get(parent_ir.operator_id, ())
                ),
                design_rationale=(
                    "Bounded offline parameter variation for cross-domain "
                    "candidate-lifecycle qualification."
                ),
                budget_declaration=ProposalBudgetDeclaration(
                    limits={
                        "search_calls": active.search_calls,
                        "validation_instances": len(validation),
                        "runtime_repetitions": active.runtime_repetitions,
                    }
                ),
                payload=candidate_ir,
            )
            parsed = kit.parse_ir(envelope.payload)
            smoke = kit.smoke(
                parsed,
                JSSPSmokeFixture(
                    fixture_instance,
                    fixture_solution,
                    seeds=(0, 1, 2),
                ),
            )
            candidate_operator = kit.compile(parsed)
            validation_report = validator.validate(
                validation,
                population,
                parent_operator.operator_id,
                candidate_operator,
                generation=generation,
                candidate_index=candidate_index,
                root_run_id="jssp-offline-smoke",
                safety_failures=smoke.failures,
                persist_evidence=persist_evidence,
            )
            if validation_report.retained:
                population[slot] = candidate_operator
                specs.pop(parent_operator.operator_id)
                specs[candidate_operator.operator_id] = parsed
            records.append(
                CandidateLifecycleRecord(
                    generation=generation,
                    candidate_index=candidate_index,
                    candidate_id=candidate_operator.operator_id,
                    parent_id=parent_operator.operator_id,
                    envelope_hash=envelope.envelope_hash,
                    smoke_passed=smoke.smoke_passed,
                    validation_outcomes=len(validation_report.outcomes),
                    parent_mean_best_makespan=float(
                        np.mean(
                            [
                                outcome.parent_best_cost
                                for outcome in validation_report.outcomes
                            ]
                        )
                    ),
                    candidate_mean_best_makespan=float(
                        np.mean(
                            [
                                outcome.candidate_best_cost
                                for outcome in validation_report.outcomes
                            ]
                        )
                    ),
                    mean_gain=validation_report.mean_gain,
                    parent_feasibility_rate=(
                        validation_report.parent_feasibility_rate
                    ),
                    candidate_feasibility_rate=(
                        validation_report.candidate_feasibility_rate
                    ),
                    median_parent_runtime_ms=float(
                        np.median(
                            [
                                outcome.parent_runtime_ms
                                for outcome in validation_report.outcomes
                            ]
                        )
                    ),
                    median_candidate_runtime_ms=float(
                        np.median(
                            [
                                outcome.candidate_runtime_ms
                                for outcome in validation_report.outcomes
                            ]
                        )
                    ),
                    candidate_effective_call_rate=(
                        validation_report.candidate_effective_call_rate
                    ),
                    candidate_acceptance_rate=(
                        validation_report.candidate_operator_acceptance_rate
                    ),
                    retained=validation_report.retained,
                    retention_reasons=list(validation_report.retention_reasons),
                )
            )

    final_ids = [operator.operator_id for operator in population]
    fingerprint = population_fingerprint(final_ids, specs, kit)
    freeze_receipt = splits.freeze_population(final_ids, fingerprint)
    trace_count = len(recorder) if recorder is not None else 0
    report = JSSPEvolutionSmokeReport(
        master_seed=active.master_seed,
        search_calls=active.search_calls,
        generations=active.generations,
        candidates_per_generation=active.candidates_per_generation,
        validation_instances=len(validation),
        runtime_repetitions=active.runtime_repetitions,
        initial_population_ids=initial_ids,
        final_population_ids=final_ids,
        candidate_records=records,
        trace_count=trace_count,
        freeze_receipt_id=freeze_receipt.receipt_id,
        final_population_fingerprint=fingerprint,
    )
    return JSSPEvolutionSmokeOutcome(
        report=report,
        freeze_receipt=freeze_receipt,
        final_population=tuple(population),
        final_ir_by_id=dict(specs),
    )


__all__ = [
    "CandidateLifecycleRecord",
    "JSSPEvolutionSmokeConfig",
    "JSSPEvolutionSmokeOutcome",
    "JSSPEvolutionSmokeReport",
    "run_offline_evolution_smoke",
]
