"""Operator designer interfaces and implementations."""

from .design_models import (
    CandidateStatus,
    DesignHypothesis,
    DiagnosisClaim,
    DiagnosisReport,
    OperatorDesignResult,
    OperatorReview,
)
from .designer_base import OperatorDesigner, OperatorProposal
from .evidence import (
    CaseSummary,
    ContextEvidence,
    CounterfactualEvidence,
    DesignBudget,
    EvidenceBundleBuilder,
    FailureEvidence,
    OperatorEvidenceBundle,
    SynergyEvidence,
)
from .heuristic_designer import HeuristicDesigner
from .llm_designer import LLMDesignerAdapter
from .multi_agent import (
    CandidateCritique,
    CandidatePortfolio,
    DeterministicCritic,
    DeterministicMockMultiAgent,
    DeterministicMockMultiAgentResearch,
    ExploitationDesigner,
    ExplorationDesigner,
    MULTI_AGENT_BUDGET,
    MultiAgentCoordinator,
    MultiAgentRoleTrace,
    PortfolioCandidate,
    PortfolioCritique,
    PortfolioScoreComponents,
    RoleTrace,
)
from .orchestrator import (
    DesignMode,
    OperatorDesignOrchestrationResult,
    OperatorDesignOrchestrator,
    OperatorDesignRequest,
    ReviewMode,
)
from .prompts import (
    EXPLOITATION_DESIGNER_V1,
    EXPLORATION_DESIGNER_V1,
    PORTFOLIO_CRITIC_V1,
    PromptTemplate,
    get_prompt_template,
)
from .proposal_validation import ProposalValidationError, ProposalValidator
from .providers import (
    LLMCallConfig,
    LLMCallRecord,
    LLMProvider,
    MockLLMProvider,
    OpenAIProvider,
)
from .research_agent import (
    CandidateAttempt,
    DeterministicMockResearchAgent,
    OpenAIAgentsResearchAgent,
    ResearchAgentBackend,
    ResearchAgentResult,
    evaluate_candidate_attempt,
)
from .tools import (
    AUTHORIZED_TOOL_NAMES,
    AgentBudget,
    AgentBudgetController,
    AgentToolContext,
    AgentToolDispatcher,
    AgentUsage,
    SmokeTestFixture,
)
from .audit import (
    AgentAuditStore,
    AgentRunRecord,
    AgentToolCallRecord,
    AgentBudget as AuditAgentBudget,
    AgentUsage as AuditAgentUsage,
    CandidateEventRecord,
    EvidenceBundleRecord,
    LLMCallRecord as AuditLLMCallRecord,
)

__all__ = [
    "CandidateStatus",
    "CandidateAttempt",
    "CandidateCritique",
    "CandidatePortfolio",
    "CandidateEventRecord",
    "CaseSummary",
    "ContextEvidence",
    "CounterfactualEvidence",
    "DesignBudget",
    "DesignHypothesis",
    "DiagnosisClaim",
    "DiagnosisReport",
    "EvidenceBundleBuilder",
    "FailureEvidence",
    "HeuristicDesigner",
    "LLMCallConfig",
    "LLMCallRecord",
    "LLMProvider",
    "LLMDesignerAdapter",
    "DesignMode",
    "MockLLMProvider",
    "OpenAIProvider",
    "OperatorDesignResult",
    "OperatorDesignOrchestrationResult",
    "OperatorDesignOrchestrator",
    "OperatorDesignRequest",
    "OperatorDesigner",
    "OperatorEvidenceBundle",
    "OperatorProposal",
    "OperatorReview",
    "ProposalValidationError",
    "ProposalValidator",
    "PromptTemplate",
    "get_prompt_template",
    "ResearchAgentBackend",
    "ResearchAgentResult",
    "ReviewMode",
    "DeterministicMockResearchAgent",
    "DeterministicCritic",
    "DeterministicMockMultiAgent",
    "DeterministicMockMultiAgentResearch",
    "ExploitationDesigner",
    "ExplorationDesigner",
    "MultiAgentCoordinator",
    "MultiAgentRoleTrace",
    "OpenAIAgentsResearchAgent",
    "AUTHORIZED_TOOL_NAMES",
    "AgentBudget",
    "AgentBudgetController",
    "AgentToolContext",
    "AgentToolDispatcher",
    "AgentUsage",
    "SmokeTestFixture",
    "AgentAuditStore",
    "AgentRunRecord",
    "AgentToolCallRecord",
    "AuditAgentBudget",
    "AuditAgentUsage",
    "AuditLLMCallRecord",
    "EvidenceBundleRecord",
    "EXPLOITATION_DESIGNER_V1",
    "EXPLORATION_DESIGNER_V1",
    "PORTFOLIO_CRITIC_V1",
    "PortfolioCritique",
    "PortfolioCandidate",
    "PortfolioScoreComponents",
    "RoleTrace",
    "MULTI_AGENT_BUDGET",
    "evaluate_candidate_attempt",
    "SynergyEvidence",
]
